# Generated by Django 3.1 on 2020-09-08 02:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('categoryID', models.IntegerField(primary_key=True, serialize=False)),
                ('categoryname', models.TextField()),
            ],
            options={
                'verbose_name': '科类',
                'db_table': 'Category',
            },
        ),
        migrations.CreateModel(
            name='Colleges',
            fields=[
                ('collegeID', models.IntegerField(primary_key=True, serialize=False)),
                ('collegeName', models.TextField()),
                ('project985', models.BooleanField(default=False)),
                ('project211', models.BooleanField()),
                ('top', models.BooleanField()),
            ],
            options={
                'verbose_name': '大学列表',
                'db_table': 'Colleges',
            },
        ),
        migrations.CreateModel(
            name='Firstlevel',
            fields=[
                ('firstlevelID', models.IntegerField(primary_key=True, serialize=False)),
                ('firstlevelName', models.TextField()),
                ('subjectID', models.IntegerField()),
                ('subjectName', models.TextField()),
            ],
            options={
                'verbose_name': '一级学科',
                'db_table': 'Firstlevel',
            },
        ),
        migrations.CreateModel(
            name='Provinces',
            fields=[
                ('provinceID', models.IntegerField(primary_key=True, serialize=False)),
                ('provinceName', models.TextField()),
            ],
            options={
                'verbose_name': '省份列表',
                'db_table': 'Provinces',
            },
        ),
        migrations.CreateModel(
            name='Rankings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField()),
                ('score', models.IntegerField()),
                ('rank', models.IntegerField()),
                ('categoryID', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='ormDesign.category')),
                ('provinceID', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='ormDesign.provinces')),
            ],
            options={
                'verbose_name': '排名列表',
                'db_table': 'Rankings',
            },
        ),
        migrations.CreateModel(
            name='Majors',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('majorName', models.TextField()),
                ('year', models.IntegerField()),
                ('minScore', models.IntegerField()),
                ('avgScore', models.IntegerField(null=True)),
                ('maxScore', models.IntegerField(null=True)),
                ('firstlevelIDs', models.TextField(null=True)),
                ('categoryID', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='ormDesign.category')),
                ('collegeID', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='ormDesign.colleges')),
                ('provinceID', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='ormDesign.provinces')),
            ],
            options={
                'verbose_name': '专业列表',
                'db_table': 'Majors',
            },
        ),
        migrations.AddField(
            model_name='colleges',
            name='provinceID',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='ormDesign.provinces'),
        ),
    ]
